# Site Settings
title: MyBlog | Vimal Krishna
email: vimal.krishna.84 (at) gmail.com
description: Err... May I say something?
baseurl: ""
url: "https://vimal-krishna.github.io" 
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Vimal_K
user_description: Software Someone
disqus_username: https-vimal-krishna-github-io

# Social Media
# Remove the item if you don't need it
github_username: vimal-krishna
#facebook_username: 
twitter_username: v1malkr1shna
#instagram_username: 
linkedin_username: vimalkrishna
#medium_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
