# Site Settings
title: MyBlog | Vimal Krishna
email: vimal.krishna.84 (at) gmail.com
description: Err... May I say something?
baseurl: ""
url: "https://vimal-krishna.github.io" #"https://www.rossener.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Vimal_K
user_description: Software Someone
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: vimal-krishna
facebook_username: datvichrox
twitter_username: guitarvimal
instagram_username: datvichrox
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
